### ISSUE TITLE
500 internal server for badge

### ISSUE THREAD

**Issue by sneumann** [niccokunzmann/dockerhub-build-status-image#15]
Hi, I am getting a `500` for 

https://dockerbuildbadges.quelltext.eu/status.svg?organization=bioconductor&repository=release_cytometry2

although it exists and builds just fine:
https://hub.docker.com/r/bioconductor/release_cytometry2/builds

while another image at the same organisation is just fine:
https://dockerbuildbadges.quelltext.eu/status.svg?organization=bioconductor&repository=release_base2

Anything simple I can do to fix ? Yours, Steffen

**Comment by sneumann** [comment]
Ok, I switched over to shields.io as badge provider, 
which gives me a "repo not found". Although I couldn't find 
where I have the typo. Sorry for the noise here, Yours, Steffen

**Comment by niccokunzmann** [comment]
I read in the other issue that the dockerhub api changed for newer repos.
Maybe, you can have a look at the shields' issues if they have the same
problem.
Tell us, if you find something :)

**Comment by sneumann** [comment]
Indeed, the two unfound repos / 500 status are the two recent images/repos on docker hub.
Unfortunately I have no idea how to debug here. Yours, Steffen

**Comment by niccokunzmann** [comment]
In this case, you can team up in
https://github.com/niccokunzmann/dockerhub-build-status-image/issues/14
and close this issue. Maybe you have an idea how to use the API v3.
