### ISSUE TITLE
Route "/" should show something useful

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/dockerhub-build-status-image#3]
The / should show something to the user, not an error.

- [x] link to this repository
- [x] explain shortly what this is about
- [x] embed an example
- [x] Let the user download the source code of the server

add a `@get("/")` to the Python server source code to serve this html content.

**Comment by gurditsbedi** [comment]
hey @niccokunzmann,

so as a first-timer, i am going to resolve this issue. The major work is done. 
What is to be written in "explain shortly what this is about"?

Completing this i will be able to do a pull request.

**Comment by niccokunzmann** [comment]
@gurditsbedi Welcome! I think this sentence from the README would be enough:

> Show status badges of your dockerhub automated build in your README.md (like those for travis).

So the  viewers know what this server is supposed to do.

You can also create several pull-requests or unfinished ones. This way, we can collaborate.
Best, 
Nicco

**Comment by gurditsbedi** [comment]
I have made a pull request. :smile:

**Comment by niccokunzmann** [comment]
@gurditsbedi Thanks!

The current source of the sevrer is always available at "/source".
https://github.com/niccokunzmann/dockerhub-build-status-image/blob/master/python-server/dockerhub_status_image_api.py#L69
This is the idea behind AGPL: we can always retrieve the ccurrent working source even for old or adapted servers so be sure what is going on.

**Comment by niccokunzmann** [comment]
@gurditsbedi Your changes are live :) https://dockerbuildbadges.quelltext.eu/ Thanks!
