### ISSUE TITLE
Add link to source code

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/dockerhub-build-status-image#7]
In order to allow people viewing this to contribute back, there should be a link in the files they see.
There are different ways to add links to these files:

- [ ] in README.md
- [x] in status.svg
- [x] in status.svg of [the Python server line 20](https://github.com/niccokunzmann/dockerhub-build-status-image/blob/master/python-server/dockerhub_status_image_api.py#L20)

**Comment by imshashwataggarwal** [comment]
Hi @niccokunzmann , I am a first timer. Could you guide me how to get going on the issue.

**Comment by niccokunzmann** [comment]
@imshashwataggarwal welcome!
So: The idea is to add links to aditional files. The problem: The image is used here: https://github.com/loklak/loklak_server#loklak
But if there is a problem with it, other people can not find out how to solve it. So, there should be the url of this project somewhere in the svg file.

e.g. in the https://github.com/niccokunzmann/dockerhub-build-status-image/blob/master/status.svg file, you can add a link to this repository somewhere.

You can edit the file online or on your computer.
How familiar are you with git and github, what would you like to do and try?

**Comment by niccokunzmann** [comment]
Ah, I see you already contributed on github

**Comment by imshashwataggarwal** [comment]
#9 Added Link to  https://github.com/niccokunzmann/dockerhub-build-status-image/blob/master/status.svg file.

**Comment by niccokunzmann** [comment]
@imshashwataggarwal Thanks! I checked the box.

**Comment by niccokunzmann** [comment]
The same svg file is inside [the Python server line 20](https://github.com/niccokunzmann/dockerhub-build-status-image/blob/master/python-server/dockerhub_status_image_api.py#L20)

**Comment by imshashwataggarwal** [comment]
#10  Added Link to svg file inside the [Python server line 20](https://github.com/niccokunzmann/dockerhub-build-status-image/blob/master/python-server/dockerhub_status_image_api.py#L20)

**Comment by niccokunzmann** [comment]
@imshashwataggarwal Your changes are live :)
https://dockerbuildbadges.quelltext.eu/status.svg?organization=mariobehling&repository=loklak
